# -*- coding: utf-8 -*-
"""POS_tagging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1McpDr3gVhmlrhDoZrFFMvvqkzOq7K0vM
"""

import nltk

nltk.download()

nltk.download('punkt')

paragraph = """ Natural language processing (NLP) is a subfield of Artificial Intelligence (AI). This is a widely used technology for personal assistants that are used in various business fields/areas. This technology works on the speech provided by the user breaks it down for proper understanding and processes it accordingly. This is a very recent and effective approach due to which it has a really high demand in today’s market. Natural Language Processing is an upcoming field where already many transitions such as compatibility with smart devices, and interactive talks with a human have been made possible. Knowledge representation, logical reasoning, and constraint satisfaction were the emphasis of AI applications in NLP. Here first it was applied to semantics and later to grammar. In the last decade, a significant change in NLP research has resulted in the widespread use of statistical approaches such as machine learning and data mining on a massive scale. The need for automation is never-ending courtesy of the amount of work required to be done these days. NLP is a very favorable, but aspect when it comes to automated applications. The applications of NLP have led it to be one of the most sought-after methods of implementing machine learning. Natural Language Processing (NLP) is a field that combines computer science, linguistics, and machine learning to study how computers and humans communicate in natural language. The goal of NLP is for computers to be able to interpret and generate human language. This not only improves the efficiency of work done by humans but also helps in interacting with the machine. NLP bridges the gap of interaction between humans and electronic devices.

Natural Language Processing (NLP) is a subfield of artificial intelligence that deals with the interaction between computers and humans in natural language. It involves the use of computational techniques to process and analyze natural language data, such as text and speech, with the goal of understanding the meaning behind the language.

NLP is used in a wide range of applications, including machine translation, sentiment analysis, speech recognition, chatbots, and text classification."""

"""**Tokenization**

**Sentence Tokenization**
"""

sentences = nltk.sent_tokenize(paragraph)

sentences

"""**Word Tokenization**"""

words = nltk.word_tokenize(paragraph)

words

"""**Stemming**"""

from nltk.stem import PorterStemmer

nltk.download('stopwords')

from nltk.corpus import stopwords

stopwords.fileids()

stemmer = PorterStemmer()

for i in range(len(sentences)):
  words = nltk.word_tokenize(sentences[i])
  words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
  sentences[i] = ' '.join(words)

words

"""**Lemmatization**"""

from nltk.stem import WordNetLemmatizer

from nltk.corpus import stopwords

sentences = nltk.sent_tokenize(paragraph)

lemmatizer = WordNetLemmatizer()

nltk.download('wordnet')

for i in range(len(sentences)):
  words = nltk.word_tokenize(sentences[i])
  words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
  sentences[i] = ' ' .join(words)

words

word_tokenizer = nltk.word_tokenize(paragraph)

nltk.download('averaged_perceptron_tagger')

pos = nltk.pos_tag(word_tokenizer)

pos

for i in range(0, len(pos)):
  if(pos[i][1]=='NNS'):
    print(pos[i][0])

nltk.download('tagsets')

nltk.help.upenn_tagset('VBG')

